AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  msk-auth-sam

  Sample SAM Template for msk-auth-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  InitializeACMPCA:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: init_acm_pca/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
Outputs:
  ACMPCAInitFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt InitializeACMPCA.Arn
